language: ruby
rvm:
  - 2.3.3

sudo: false
branches:
  only:
    - src

cache:
  cargo: false
  bundler: false

before_install:
  - # sudo apt-get -qq update
  - sudo apt-get install -y tree

install:
  - gem install jekyll
  - gem install jekyll-paginate
  - gem install jekyll-gist
  - gem install github-pages
  - gem install jekyll-sitemap
  - gem install jekyll-seo-tag
  - gem install redcarpet
  - wget -O "$HOME/bin/mdbook" https://github.com/donald-pinckney/mdBook/releases/latest/download/mdbook
  - chmod +x "$HOME/bin/mdbook"
  - mdbook --version

script: ./buildToMaster
env:
  global:
    - ENCRYPTION_LABEL: "f45b69d04d69"
    - COMMIT_AUTHOR_EMAIL: "donald_pinckney@icloud.com"

