# Permalinks

# Setup
title:            Donald Pinckney
description:      'PhD student researching programming languages at Northeastern University.'
url:              https://donaldpinckney.com
baseurl:          ""
timezone:         America/Los_Angeles
exclude:          ['deploy', 'nonsite']
repo:             https://github.com/donald-pinckney/donald-pinckney.github.io
author:
  name:           'Donald Pinckney'
  email:          donald_pinckney@icloud.com

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
social:
  github: donald-pinckney
  twitter: donald_pinckney
  email: 'donald_pinckney@icloud.com'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - github-pages
  - jekyll-sitemap
  - jekyll-seo-tag
  - redcarpet

# Sitemap stuff
sitemap:
  include_posts:
    - "/index.html"

# Plugins
plugins_dir: [jekyll-sitemap, jekyll-seo-tag, _plugins]

# Subscription issues
subscription_issues:
  TensorFlow: https://github.com/donald-pinckney/donald-pinckney.github.io/issues/18
  Metal: https://github.com/donald-pinckney/donald-pinckney.github.io/issues/17
  PyTorch: https://github.com/donald-pinckney/donald-pinckney.github.io/issues/21

markdown: Runnable

host: 0.0.0.0
